### ISSUE TITLE
Remove typing library requirement

### ISSUE THREAD

**Issue by WildCard65** [camas/setuptools-git-ver#2]
@dolfinus Would it be possible for you to remove the requirement for the typing module? It doesn't support Python 3.3, if not, I'll just maintain a fork your fork for myself.

**Comment by dolfinus** [comment]
Hello.

Actually, you're writing wrong repo. My repo is https://github.com/dolfinus/setuptools-git-versioning.

I've just added python3.3 and 3.4 support here, please check: https://pypi.org/project/setuptools-git-versioning/1.1.8/

**Comment by WildCard65** [comment]
@dolfinus I'm aware of what repo I opened this against, yours doesn't have an Issues page available so I had to resort to here.

**Comment by dolfinus** [comment]
Ok, I've enabled issues tab.
